server:
  port: 8900

spring:
  data:
    redis:
      host: 192.168.200.140
      port: 6379
      password: xxx
      database: 0

  rabbitmq:
    host: 192.168.200.140
    port: 5672
    username: xxx
    password: xxx
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
  elasticsearch:
    uris: http://192.168.200.140:9200
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

app:
  threadpool:
    corePoolSize: 500
    maxPoolSize: 1000
    queueSize: 500

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl